### ISSUE TITLE
Publish latest changes to Ansible Galaxy

### ISSUE THREAD

**Issue by kishorenc** [Oefenweb/ansible-conntrack#4]
Thanks for making this available! Please do publish your latest changes to Galaxy: https://galaxy.ansible.com/tersmitten/conntrack/

(Bare variables are deprecated in Ansible 2, and I see that you've already fixed that, but have not published the changes to Galaxy).

**Comment by tersmitten** [comment]
Done

**Comment by kishorenc** [comment]
Maybe I am not looking at the right place, but I still don't see the latest release reflected on [Galaxy:](https://galaxy.ansible.com/tersmitten/conntrack/)

<img width="756" alt="screen shot 2016-12-01 at 4 33 09 pm" src="https://cloud.githubusercontent.com/assets/782073/20791613/e507ad8c-b7e3-11e6-9403-ebb9557f08e8.png">

**Comment by tersmitten** [comment]
`1.0.1` contains the Ansible 2 fixes:

```
# git diff origin/master v1.0.1 
diff --git a/.travis.yml b/.travis.yml
index 91b2221..06a0594 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,10 +7,6 @@ python: "2.7"
 
 env:
   - ANSIBLE_VERSION=latest
-  - ANSIBLE_VERSION=2.2.0.0
-  - ANSIBLE_VERSION=2.1.3
-  - ANSIBLE_VERSION=2.1.2
-  - ANSIBLE_VERSION=2.1.1.0
   - ANSIBLE_VERSION=2.1.0.0
   - ANSIBLE_VERSION=2.0.2.0
   - ANSIBLE_VERSION=2.0.1.0
diff --git a/Vagrantfile b/Vagrantfile
index e4fb02a..585a8d9 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -6,42 +6,48 @@ role = File.basename(File.expand_path(File.dirname(__FILE__)))
 boxes = [
   {
     :name => "ubuntu-1004",
-    :box => "bento/ubuntu-10.04",
+    :box => "opscode-ubuntu-10.04",
+    :url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04_chef-provisionerless.box",
     :ip => '10.0.0.10',
     :cpu => "50",
     :ram => "256"
    },
   {
     :name => "ubuntu-1204",
-    :box => "bento/ubuntu-12.04",
+    :box => "opscode-ubuntu-12.04",
+    :url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box",
     :ip => '10.0.0.11',
     :cpu => "50",
     :ram => "256"
   },
   {
     :name => "ubuntu-1404",
-    :box => "bento/ubuntu-14.04",
+    :box => "opscode-ubuntu-14.04",
+    :url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box",
     :ip => '10.0.0.12',
     :cpu => "50",
     :ram => "256"
   },
   {
     :name => "debian-6010",
-    :box => "bento/debian-6.0.10",
+    :box => "opscode-debian-6.0.10",
+    :url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.10_chef-provisionerless.box",
     :ip => '10.0.0.13',
     :cpu => "50",
     :ram => "256"
   },
   {
     :name => "debian-711",
-    :box => "bento/debian-7.11",
+    :box => "opscode-debian-7.11",
+    :url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.11_chef-provisionerless.box",
     :ip => '10.0.0.14',
     :cpu => "50",
     :ram => "256"
   },
   {
-    :name => "debian-86",
-    :box => "bento/debian-8.6",
+    :name => "debian-85",
+    :box => "opscode-debian-8.5",
+    :url => "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-8.5_chef-provisionerless.box",
     :ip => '10.0.0.15',
     :cpu => "50",
     :ram => "256"
@@ -52,6 +58,7 @@ Vagrant.configure("2") do |config|
   boxes.each do |box|
     config.vm.define box[:name] do |vms|
       vms.vm.box = box[:box]
+      vms.vm.box_url = box[:url]
       vms.vm.hostname = "ansible-#{role}-#{box[:name]}"
 
       vms.vm.provider "virtualbox" do |v|
```

I can tag a new release if it's necessary, but I'm not sure that it will fix things for you.

**Comment by kishorenc** [comment]
Yes, I think tagging and re-publishing would work. For e.g. I just did a clean install of v1.0.1 and still found `with_items: conntrack_kernel_modules` instead of `with_items: "{{ conntrack_kernel_modules }}"`.

**Comment by tersmitten** [comment]
I was looking at the diff of another role :-( I tagged a new release (`v1.0.2`). I hope everything is fine now.
